### ISSUE TITLE
`\t` in a file throws unwarranted error

### ISSUE THREAD

**Issue by sdglitched** [gridhead/gi-loadouts#331]
`\t` in any position of a file throws unwarranted error when trying to load it.

![Image](https://github.com/user-attachments/assets/4f3a5e8e-dc54-49e5-9160-fd477b30ca69)

```yaml
area: FWOL
levl: Level 00
name: Adventurer's Flower
rare: 1
stat:
  a:
    data: 1.0
    name: ATK %
  b:
    data: 0.0
    name: None
  c:
    data: 0.0
    name: None	
  d:
    data: 0.0
    name: None
  main:
    data: 129.0
    name: HP
type: Adventurer
```

Throw a custom error message or if possible do some data validation before trying to parse the file.
