### ISSUE TITLE
Check validity of artifact area before loading instead of doing simultaneously

### ISSUE THREAD

**Issue by sdglitched** [gridhead/gi-loadouts#332]
Check validity of artifact area before loading instead of doing simultaneously.

Currently any artifact file of a particular area can be loaded into another area, but it does it with incorrect main and substats as they vary depending on which area the artifact is of.

![Image](https://github.com/user-attachments/assets/818d9d96-ca5f-4d34-be04-dde5fb100299)

```yaml
area: SDOE
levl: Level 20
name: Undying One's Mourning Bell
rare: 5
stat:
  a:
    data: 1.0
    name: ATK
  b:
    data: 1.0
    name: ATK %
  c:
    data: 1.0
    name: ATK
  d:
    data: 1.0
    name: ATK
  main:
    data: 51.8
    name: Energy Recharge
type: Long Night's Oath
```

Either raise an exception if trying to load a artifact file of one type in another type or check for the data validity.

Better to raise an exception instead of validation. 😏
